### ISSUE TITLE
Update tags on repository for bower happiness

### ISSUE THREAD

**Issue by elskwid** [joshfire/woodman#23]
I just submitted a pull request for an updated `bower.json` file (#22). Looking over the bower documentation it also recommends _semver_ git tags.

> - There must be a valid manifest JSON in the current working directory.
> - Your package should use semver Git tags.
> - Your package must be available at a Git endpoint (e.g., GitHub); remember to push your Git tags!

It looks like the first and last items are good. I would be happy to track back through the commits and create tags for older releases if that would help.

Thanks for a great project!

**Comment by tidoust** [comment]
Forgot to mention that Woodman will use Git tags from now on. It already follows _semver_ conventions.
I don't think we need to create tags for older releases but let me know if that sounds needed.

**Comment by elskwid** [comment]
@tidoust - this is great news!

As far as posting the old tags it's only needed if you want to allow people to download the old versions through bower.

For instance, if you do `bower info woodman` now you get the following for versions:

```
Available versions:
  - 0.9.0
  - 0.8.0
```

Which means you can do `bower info woodman#0.9.0` or `bower info woodman#0.8.0` but nothing earlier.

```
$ bower info woodman#0.7.0

bower woodman#0.7.0         not-cached git://github.com/joshfire/woodman.git#0.7.0
bower woodman#0.7.0            resolve git://github.com/joshfire/woodman.git#0.7.0
bower woodman#0.7.0       ENORESTARGET No tag found that was able to satisfy 0.7.0
```

Unlike RubyGems or something similar, bower doesn't store the created package, it uses the git endpoint (tag).

Thanks again.
